language: cpp

matrix:
  include:

  - name: "Linux clang static linking"
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - libgtk-3-dev
          - libvulkan-dev
          - llvm-7-dev
    compiler: clang
    env:
     - CMAKE_FLAGS="-DXENIA_LINK_SHARED=OFF -DPython3_EXECUTABLE=/usr/bin/python3"

  - name: "Linux clang shared linking"
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          - libgtk-3-dev
          - libvulkan-dev
          - llvm-7-dev
    compiler: clang
    env:
     - CMAKE_FLAGS="-DXENIA_LINK_SHARED=ON -DPython3_EXECUTABLE=/usr/bin/python3"

script:
  - mkdir build && cd build
  - cmake $CMAKE_FLAGS ..
  - cmake --build .

